# Dated 29 May, 2025

In [2]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [14]:
list=[1,2,3,4,5]
print(list*5)

np_array=np.array([1,2,3])
np_array*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 5, 10, 15])

In [ ]:
# zero matrix
zeroes=np.zeros((3,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# one matrix
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 5 x 5 Identity matrix
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr=np.linspace(1,100,6)
arr

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [ ]:
arr=np.arange(0,10,3) # generates an array
arr

array([0, 3, 6, 9])

In [ ]:
# 8 array
arr=np.full((2,3),8)
arr

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
# random number generation
arr=np.random.rand(4,5)
arr

array([[0.53222791, 0.77460405, 0.86591242, 0.57698547, 0.260096  ],
       [0.27887421, 0.43309197, 0.61372617, 0.55362272, 0.34629198],
       [0.0307092 , 0.84568443, 0.47015359, 0.80870837, 0.21267649],
       [0.97102949, 0.72173853, 0.95036681, 0.32942937, 0.52565163]])

In [32]:
arr=np.random.rand(6,7)*100
arr

array([[21.77080601, 27.80090944, 79.47841338, 93.3917636 , 92.73951944,
        29.32496345, 78.74310087],
       [ 0.89547663, 42.85501611, 92.89578426, 69.58283528, 93.67237962,
        61.12874623, 97.92765423],
       [86.59035879, 50.0411803 , 78.68118544, 65.85470991, 79.19645424,
        30.01556129, 30.33567477],
       [85.44844594, 83.42818558, 62.80524157,  0.46431265, 79.93403148,
         2.04932505, 16.79344292],
       [13.34502016, 84.07446432, 39.39014032, 49.77130009, 40.50354031,
         4.77221449, 50.82475508],
       [61.81584883, 71.04312931, 71.46726705, 11.74647696, 33.93768323,
        44.41335852, 85.95166676]])

In [37]:
arr=np.random.randint(size=(2,4),low=5)
arr

array([[0, 1, 4, 2],
       [4, 3, 2, 3]], dtype=int32)

In [39]:
arr.astype(float)

array([[0., 1., 4., 2.],
       [4., 3., 2., 3.]])

In [44]:
arr=np.random.rand(4,5)
arr.astype(int).astype(bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [48]:
arr=np.array([1,2,3])
print(f'Array-->{arr}')
print(f'List-->{arr.tolist()}')

Array-->[1 2 3]
List-->[1, 2, 3]


In [50]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If 

In [ ]:
# output number of elements in the array
arr.size

3

In [57]:
arr=np.array([[1,2,3],
              [4,5,6]])
# outputs (rows, columns) of the matrix (dimensions)
arr.shape

(2, 3)

In [62]:
arr=np.random.rand(3,4)
# output the datatype of the elements of the array
arr.dtype

dtype('float64')

In [72]:
arr1=np.copy(arr)
print(arr1)

[[0.14031593 0.39102567 0.97331147 0.28763184]
 [0.27800982 0.56197401 0.918975   0.35940862]
 [0.58030309 0.26126481 0.47055838 0.23520342]]


In [ ]:
arr1=np.random.rand(2,3)
print(arr1)
arr2=np.copy(arr1)
print(arr2)
arr3=arr1
print(arr3)


[[0.85564409 0.59011823 0.35742682]
 [0.59569338 0.65086854 0.77652769]]
[[0.85564409 0.59011823 0.35742682]
 [0.59569338 0.65086854 0.77652769]]
[[0.85564409 0.59011823 0.35742682]
 [0.59569338 0.65086854 0.77652769]]


In [79]:
arr=np.random.rand(2,3)
print(arr)
print(arr.view(int))

[[0.37024496 0.96793019 0.23294832]
 [0.01032433 0.26081845 0.69475662]]
[[4600341360184120316 4606893559663154129 4597560868126624784]
 [4577105192857625024 4598370107452942892 4604433030860238961]]


In [86]:
arr=np.random.rand(2,3)
print(arr)
arr.sort()
print(arr)

[[0.88858749 0.66846942 0.72680004]
 [0.41521957 0.56078483 0.17361936]]
[[0.66846942 0.72680004 0.88858749]
 [0.17361936 0.41521957 0.56078483]]


In [89]:
arr_2d=np.array([[3,4],[1,2]])
print(arr_2d)
arr_2d.flatten()

[[3 4]
 [1 2]]


array([3, 4, 1, 2])

In [94]:
arr=np.array([[1,2,3],[10,20,30]])
print(arr)
# prints transpose matrix
print(arr.T)

[[ 1  2  3]
 [10 20 30]]
[[ 1 10]
 [ 2 20]
 [ 3 30]]


In [93]:
# alternates row values with column values
arr.reshape(3,2)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [3]:
arr=np.random.rand(2,3)
print(arr)
arr.resize(5,6)
print(arr)

[[0.92172904 0.59515962 0.35175625]
 [0.78429139 0.93508447 0.85532786]]
[[0.92172904 0.59515962 0.35175625 0.78429139 0.93508447 0.85532786]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [5]:
arr=np.random.rand(2,3)
print(arr)

print(np.append(arr,1))


[[0.40897148 0.16710853 0.01585929]
 [0.49069686 0.88487265 0.3706714 ]]
[0.40897148 0.16710853 0.01585929 0.49069686 0.88487265 0.3706714
 1.        ]


In [6]:
print(np.insert(arr,2,2))

[0.40897148 0.16710853 2.         0.01585929 0.49069686 0.88487265
 0.3706714 ]


In [10]:
arr=np.random.rand(3,4)
print(arr)
# deletes row 1 (indexed from 0) because axis=0
arr=np.delete(arr,1,axis=0)
print(arr)
# deletes row 1 (indexed from 0) because axis=1
arr=np.delete(arr,1,axis=1)
print(arr)

[[0.39291202 0.52595469 0.41013993 0.23302289]
 [0.7978976  0.40822297 0.35762721 0.82994069]
 [0.11787175 0.14017603 0.42154518 0.04985337]]
[[0.39291202 0.52595469 0.41013993 0.23302289]
 [0.11787175 0.14017603 0.42154518 0.04985337]]
[[0.39291202 0.41013993 0.23302289]
 [0.11787175 0.42154518 0.04985337]]


In [22]:
arr1=np.random.randint(size=(2,3),low=100)
print(arr1)
arr2=np.random.randint(size=(2,3),low=100)
print(arr2)
print()
print(np.concatenate((arr1,arr2),axis=0))
print()
print(np.concatenate((arr1,arr2),axis=1))


[[75 83 53]
 [37 39 17]]
[[46 60 68]
 [75 58 82]]

[[75 83 53]
 [37 39 17]
 [46 60 68]
 [75 58 82]]

[[75 83 53 46 60 68]
 [37 39 17 75 58 82]]


In [29]:
# splits the array into n sub-arrays where n<=number of rows in the array
print(np.split(arr2,1))
print(np.split(arr2,2))

[array([[46, 60, 68],
       [75, 58, 82]], dtype=int32)]
[array([[46, 60, 68]], dtype=int32), array([[75, 58, 82]], dtype=int32)]


In [78]:
# hsplit splits the array into 4 number of splits
arr=np.random.randint(size=(3,4),low=50)
print(arr)
print()
print(np.hsplit(arr,2))

[[27 44 18 31]
 [25 32  8 43]
 [49 33 38 41]]

[array([[27, 44],
       [25, 32],
       [49, 33]], dtype=int32), array([[18, 31],
       [ 8, 43],
       [38, 41]], dtype=int32)]


In [62]:
# arr=np.random.randint(size=(2,2),low=50)
arr=np.array([[1,2,3]])
# for 1d array indexing
arr=np.array([1,2,3])
print(arr[1])
# for 2d array indexing
arr=np.array([[1,2,3]])
print(arr[0,2])
# for 3d array indexing
arr=np.array([[[1,2,3]]])
print(arr[0,0,0])


2
3
1


In [75]:
arr=np.random.randint(size=(2,3),low=50)
print(arr)
print()
print(arr[1:])

[[19 36 18]
 [ 7 15  5]]

[[ 7 15  5]]


In [ ]:
arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.array_equal(arr1,arr2))
print(np.log(np.array([1,2,3])))


[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[0.25 0.4  0.5 ]]
[[  1  32 729]]
False
[[0.         0.69314718 1.09861229]]
